### ISSUE TITLE
HU01 - Formulario de cadastro do carro

### ISSUE THREAD

**Issue by elzosantos** [elzosantos/meucarro#1]
Eu como usuário gostaria de ter um cadastro para o meu carro com os seguintes campos.

Marca
Modelo
Ano
Quilometragem
Revisão
Oficina
Data da Revisão
Valor
Produtos
Serviços
Estado

**Comment by georgenesalves** [comment]
Também acho interessante pensar como um comprador do carro pensaria, ou seja, quais são os itens que ele vai quere avaliar em um automóvel quando ele está pesquisando para comprar.
Talvez seriam detalhes que parecem desnecessários e que até poderiam ser alternativos o seu preenchimento, mas talvez seja de interesse quando a pessoa já tem a intenção de vender. 
Inclusive essas informações poderiam até ficar disponíveis temporariamente a uma pessoa que se interessou de ver as anotações. Uma liberação por um período de tempo, que nem a localização do Google maps do seu endereço.; lembra?
Então, pensando como um comprador, eu adicionaria estado de conservação da pintura, dos pneus, rodas, painel, algum defeito, ou algum amassado.
Se a gente pensar em carro antigo, tipo de colecionador, o cara vai querer saber se as peças são originais, etc...
